version: "0.2"
language: en
words:
  - sonarjs
  - azsce
  - aesjs
  - unpad
  - unpadded
  - unpadding
  - partialize
  - trimmable
  - codebook
  - ciphertext
  - nodebuffer
  - CAS̄
  - CNTR
  - Chrg
  - DOUT
  - Embla
  - PRECHARGE
  - PRECHARGED
  - Precharge
  - RAS̄
  - cmdk
  - nums
  - precharged
  - vaul
