version: "0.2"
language: en,ar
import:
  - "@cspell/dict-ar/cspell-ext.json"
ignoreRegExpList:
  - "/[\\u0600-\\u06FF]+/"
words:
  - NEXTAUTH
  - scannerwork
  - kiro
  - SonarQube
  - SONARQUBE
  - shinawy
  - Segoe
  - Superhost
  - sonarjs
  - azsce
  - aesjs
  - unpad
  - unpadded
  - unpadding
  - partialize
  - trimmable
  - codebook
  - ciphertext
  - nodebuffer
  - CAS̄
  - CNTR
  - Chrg
  - DOUT
  - Embla
  - PRECHARGE
  - PRECHARGED
  - Precharge
  - RAS̄
  - cmdk
  - nums
  - precharged
  - vaul
  - Shubra
  - Kheima
  - Mansoura
  - Ismailia
  - Ashmoun
  - Qena
  - Sohag
  - Hurghada
  - Sharm
  - flagcdn
  - glassmorphism
  - Français
  - dropoff
  - Dropoff
  - CARTO
  - Phonelink
  - Hassan
  - Mahmoud
  - Youssef
  - Nour
  - Saed
  - Khaled
  - appbar
  - Emirati
