import { join } from "path";
import { existsSync, copyFileSync, writeFileSync } from "fs";
import { createInterface } from "readline";

const BACKEND_DIR = join(import.meta.dir, "..", "backend");
const ENV_FILE = join(BACKEND_DIR, ".env");
const EXAMPLE_FILE = join(BACKEND_DIR, ".env.example");

async function main() {
  const args = process.argv.slice(2);
  const quick = args.includes("--quick");

  if (!existsSync(EXAMPLE_FILE)) {
    console.error(`Error: ${EXAMPLE_FILE} not found.`);
    process.exit(1);
  }

  const rl = createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  const question = (query: string): Promise<string> => {
    return new Promise((resolve) => rl.question(query, resolve));
  };

  if (existsSync(ENV_FILE) && !quick) {
    const yn = await question(".env already exists. Overwrite? [y/N] ");
    if (yn.toLowerCase() !== "y") {
      console.log("Aborted — existing .env kept.");
      process.exit(0);
    }
  }

  if (quick) {
    copyFileSync(EXAMPLE_FILE, ENV_FILE);
    console.log("✔ Copied .env.example → backend/.env");
    console.log(`  Edit ${ENV_FILE} to customise values.`);
    process.exit(0);
  }

  const ask = async (promptMsg: string, defaultVal: string, isSecret = false): Promise<string> => {
    const hint = isSecret ? "[press Enter to use default]" : `[${defaultVal}]`;
    const query = `  ${promptMsg} ${hint}: `;
    
    // For now we don't fully mask in a simple readline script, but we can instruct users.
    // Full cross-platform masking in raw Node/Bun requires capturing raw input events.
    const answer = await question(query);
    return answer.trim() === "" ? defaultVal : answer;
  };

  console.log("");
  console.log("  ╔══════════════════════════════════════╗");
  console.log("  ║   Ares Backend — .env Setup          ║");
  console.log("  ╚══════════════════════════════════════╝");
  console.log("");

  console.log("Database");
  console.log("  Inside devcontainer → host: mssql");
  console.log("  Outside devcontainer → host: localhost\n");

  const DB_HOST = await ask("SQL Server host", "localhost");
  const DB_PORT = await ask("SQL Server port", "1433");
  const DB_NAME = await ask("Database name", "ares");
  const DB_USER = await ask("Username", "sa");
  const DB_PASS = await ask("Password", "YourPassword123!", true);
  const DB_CONN = `Server=${DB_HOST},${DB_PORT};Database=${DB_NAME};User=${DB_USER};Password=${DB_PASS};TrustServerCertificate=True;Encrypt=false`;

  console.log("\nJWT");
  const JWT_KEY = await ask("Secret key (min 32 chars)", "YourSuperSecretKeyThatIsAtLeast32CharactersLong!", true);
  const JWT_ISSUER = await ask("Issuer", "AresCarRentalApi");
  const JWT_AUDIENCE = await ask("Audience", "AresCarRentalClient");
  const JWT_EXP = await ask("Token expiry (minutes)", "60");
  const JWT_EXT = await ask("Extended expiry (days)", "400");

  console.log("\nCORS — comma-separated list of allowed origins");
  const CORS_RAW = await ask("Origins", "http://localhost:3000,http://localhost:3001");

  console.log("\nASP.NET Core");
  const ASPNET_ENV = await ask("Environment", "Development");
  const ASPNET_URLS = await ask("URLs", "http://localhost:5000");

  rl.close();

  let CORS_BLOCK = "";
  const origins = CORS_RAW.split(",").map(o => o.trim()).filter(Boolean);
  origins.forEach((origin, i) => {
    CORS_BLOCK += `Cors__AllowedOrigins__${i}=${origin}\n`;
  });

  const envContent = `# Generated by scripts/setup-env.ts — do not commit this file

# Database
ConnectionStrings__DefaultConnection=${DB_CONN}

# JWT
Jwt__SecretKey=${JWT_KEY}
Jwt__Issuer=${JWT_ISSUER}
Jwt__Audience=${JWT_AUDIENCE}
Jwt__ExpirationMinutes=${JWT_EXP}
Jwt__ExtendedExpirationDays=${JWT_EXT}

# CORS
${CORS_BLOCK}
# ASP.NET Core
ASPNETCORE_ENVIRONMENT=${ASPNET_ENV}
ASPNETCORE_URLS=${ASPNET_URLS}
`;

  writeFileSync(ENV_FILE, envContent, "utf8");

  console.log(`\n✔ Written to ${ENV_FILE}\n`);
  console.log("Next steps:");
  console.log("./scripts/backend.sh   →  pick 'migrate update', then 'run'");
}

main().catch(err => {
  console.error("Setup failed:", err);
  process.exit(1);
});
