# setup-env.ps1 — generate backend/.env interactively or from defaults
#
# Usage:
#   .\scripts\setup-env.ps1           # interactive prompts
#   .\scripts\setup-env.ps1 -Quick    # copy .env.example as-is (CI / devcontainer)
#
[CmdletBinding()]
param(
    [switch]$Quick
)

$ErrorActionPreference = 'Stop'

$BackendDir  = Join-Path (Split-Path $PSScriptRoot -Parent) 'backend'
$EnvFile     = Join-Path $BackendDir '.env'
$ExampleFile = Join-Path $BackendDir '.env.example'

# ── helpers ────────────────────────────────────────────────────────────────────

function Ask([string]$Prompt, [string]$Default) {
    $value = Read-Host "  $Prompt [$Default]"
    if ([string]::IsNullOrWhiteSpace($value)) { $Default } else { $value }
}

function Ask-Secret([string]$Prompt, [string]$Default) {
    $secure = Read-Host "  $Prompt [press Enter to use default]" -AsSecureString
    $plain  = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto(
                  [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure))
    if ([string]::IsNullOrWhiteSpace($plain)) { $Default } else { $plain }
}

function Show-Header {
    Write-Host ''
    Write-Host '  ╔══════════════════════════════════════╗'
    Write-Host '  ║   Ares Backend — .env Setup          ║'
    Write-Host '  ╚══════════════════════════════════════╝'
    Write-Host ''
}

# ── guard ──────────────────────────────────────────────────────────────────────

if (-not (Test-Path $ExampleFile)) {
    Write-Error "Error: $ExampleFile not found."
    exit 1
}

if ((Test-Path $EnvFile) -and -not $Quick) {
    $yn = Read-Host '.env already exists. Overwrite? [y/N]'
    if ($yn -notmatch '^[yY]$') { Write-Host 'Aborted — existing .env kept.'; exit 0 }
}

# ── quick mode ─────────────────────────────────────────────────────────────────

if ($Quick) {
    Copy-Item $ExampleFile $EnvFile -Force
    Write-Host "✔ Copied .env.example → backend\.env"
    Write-Host "  Edit $EnvFile to customise values."
    exit 0
}

# ── interactive mode ───────────────────────────────────────────────────────────

Show-Header

Write-Host 'Database'
Write-Host '  Inside devcontainer  → host: mssql'
Write-Host '  Outside devcontainer → host: localhost'
Write-Host ''

$DbHost = Ask 'SQL Server host'   'localhost'
$DbPort = Ask 'SQL Server port'   '1433'
$DbName = Ask 'Database name'     'ares'
$DbUser = Ask 'Username'          'sa'
$DbPass = Ask-Secret 'Password'   'YourPassword123!'
$DbConn = "Server=${DbHost},${DbPort};Database=${DbName};User=${DbUser};Password=${DbPass};TrustServerCertificate=True;Encrypt=false"

Write-Host ''
Write-Host 'JWT'
$JwtKey      = Ask-Secret 'Secret key (min 32 chars)' 'YourSuperSecretKeyThatIsAtLeast32CharactersLong!'
$JwtIssuer   = Ask 'Issuer'                'AresCarRentalApi'
$JwtAudience = Ask 'Audience'              'AresCarRentalClient'
$JwtExp      = Ask 'Token expiry (minutes)' '60'
$JwtExt      = Ask 'Extended expiry (days)' '400'

Write-Host ''
Write-Host 'CORS — comma-separated list of allowed origins'
$CorsRaw = Ask 'Origins' 'http://localhost:3000,http://localhost:3001'

Write-Host ''
Write-Host 'ASP.NET Core'
$AspNetEnv  = Ask 'Environment' 'Development'
$AspNetUrls = Ask 'URLs'        'http://localhost:5000'

# ── build CORS lines ───────────────────────────────────────────────────────────

$CorsBlock = ''
$origins   = $CorsRaw -split ',' | ForEach-Object { $_.Trim() }
for ($i = 0; $i -lt $origins.Count; $i++) {
    $CorsBlock += "Cors__AllowedOrigins__${i}=$($origins[$i])`n"
}

# ── write .env ─────────────────────────────────────────────────────────────────

$content = @"
# Generated by scripts/setup-env.ps1 — do not commit this file

# Database
ConnectionStrings__DefaultConnection=$DbConn

# JWT
Jwt__SecretKey=$JwtKey
Jwt__Issuer=$JwtIssuer
Jwt__Audience=$JwtAudience
Jwt__ExpirationMinutes=$JwtExp
Jwt__ExtendedExpirationDays=$JwtExt

# CORS
$($CorsBlock.TrimEnd())

# ASP.NET Core
ASPNETCORE_ENVIRONMENT=$AspNetEnv
ASPNETCORE_URLS=$AspNetUrls
"@

# Write with UTF-8 no BOM so dotnet reads it cleanly
[System.IO.File]::WriteAllText($EnvFile, $content, [System.Text.UTF8Encoding]::new($false))

Write-Host ''
Write-Host "Written to $EnvFile"
Write-Host ''
Write-Host 'Next steps:'
Write-Host '  .\scripts\backend.ps1   →  pick ''migrate update'', then ''run'''
