using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Infrastructure.Migrations
{
    /// <inheritdoc />
    /// <summary>
    /// No-op migration.
    ///
    /// This migration was originally auto-generated by `dotnet ef migrations add`
    /// after a snapshot drift, and tried to add four columns
    /// (<c>VerificationStatus</c>, <c>RejectionReason</c>, <c>ReviewedBy</c>,
    /// <c>ReviewedAt</c>) to the <c>Drivers</c> table. Those exact columns
    /// are already added by the earlier
    /// <c>20260514120000_AddDriverLicenseAdminFields</c> migration, so applying
    /// the duplicate <c>AddColumn</c> statements crashed EF Core with
    /// "Column 'VerificationStatus' already exists on Drivers" at
    /// <c>dotnet ef database update</c> time. That in turn broke the entire
    /// driver-license / identity-verification flow at runtime because the
    /// backend could never finish starting against a fresh database.
    ///
    /// We keep the migration entry in the migration tree (so EF Core's
    /// <c>__EFMigrationsHistory</c> stays consistent with the snapshot) but
    /// strip the duplicate column additions. Both Up and Down are now
    /// intentionally empty.
    /// </summary>
    public partial class PendingModelChanges : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Intentionally empty — see class summary above.
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Intentionally empty — see class summary above.
        }
    }
}
