import type { ChapterConfig } from "../chapters";

export const appendixA: ChapterConfig = {
  id: "appendix-a",
  filename: "appendix_a.md",
  title: "Appendices - File Structure & Execution",
  heading: "APPENDIX A: APPENDICES",
  includePatterns: [
    "README.md",
    "AGENTS.md",
    "package.json",
    "scripts/setup/**",
    "scripts/docs/**",
    "frontend/package.json",
    "backend/**/*.csproj",
    ".devcontainer/**",
    ".github/**",
    ".husky/**",
    ".gitignore",
    "run-ci-tests.ps1",
  ],
  systemPrompt: [
    "You are an expert academic documentation writer for graduation projects at Al-Azhar University.",
    "Follow ProjectTemplate.md rubric. Output raw Markdown only.",
    "Include filesystem tree as Mermaid diagram referencing Figure A.x.",
  ].join(" "),
  userPrompt: [
    "Generate APPENDIX A: APPENDICES",
    "",
    "Follow ProjectTemplate.md requirements:",
    "",
    "## A.1 File Structure",
    "Provide a Mermaid diagram of the repository filesystem tree.",
    "Describe each top-level directory and its purpose.",
    "Reference: Figure A.1: Top-level filesystem tree.",
    "",
    "## A.2 System Requirements",
    "Table of all software prerequisites with versions and download URLs.",
    "",
    "## A.3 Installation and Setup",
    "Step-by-step production setup instructions.",
    "",
    "## A.4 Running the Application",
    "Docker Compose and manual startup instructions.",
    "",
    "## A.5 Development and Testing",
    "Development workflow: environment setup, running tests, code quality tools.",
    "",
    "Start with '# APPENDIX A: APPENDICES' as the top-level heading.",
  ].join("\n"),
};
