import type { ChapterConfig } from "../chapters";

export const appendixB: ChapterConfig = {
  id: "appendix-b",
  filename: "appendix_b_references.md",
  title: "References",
  heading: "APPENDIX B: REFERENCES",
  includePatterns: [
    "README.md",
    "package.json",
    "frontend/package.json",
    "backend/**/*.csproj",
    "scripts/docs/package.json",
    "scripts/setup/package.json",
  ],
  systemPrompt: "You are an academic citations specialist using APA style. Output raw Markdown only. Include a minimum of 20 references covering all frameworks, libraries, and academic sources used in the project.",
  userPrompt: [
    "Generate APPENDIX B: REFERENCES",
    "",
    "Use APA citation style. Minimum 20 references.",
    "",
    "Include references for:",
    "- Web frameworks: Next.js, React, .NET Core",
    "- Database: SQL Server, Entity Framework",
    "- Testing: xUnit, Cypress, Jest",
    "- Cloud/Infra: Docker, Kubernetes, AWS SES, AWS S3",
    "- Academic papers on car rental systems, booking algorithms, SaaS platforms",
    "- TypeScript, Material UI, Bun runtime",
    "",
    "Format examples:",
    "- Books: Gore, A. (2006). *An inconvenient truth*. Rodale.",
    "- Journals: Smith, J., & Jones, B. (2019). Cloud adoption in SMEs. *Journal of Cloud Computing*, 8, 1-21.",
    "- Industry: Microsoft. (2022). *Entity Framework Core documentation*. https://learn.microsoft.com/en-us/ef/core/",
    "",
    "All reference items must be in normal text (10pt equivalent).",
    "Include DOI links if available.",
    "Start with '# APPENDIX B: REFERENCES' as the top-level heading.",
  ].join("\n"),
};
