import type { ChapterConfig } from "../chapters";

export const chapter5: ChapterConfig = {
  id: "5",
  filename: "chapter_5_conclusion.md",
  title: "Conclusion, Impact & Future Work",
  heading: "CHAPTER 5: CONCLUSION, IMPACT & FUTURE WORK",
  includePatterns: [
    "README.md",
    "AGENTS.md",
    "package.json",
    "frontend/package.json",
    "backend/**/*.csproj",
    "backend/Api/Program.cs",
    "frontend/next.config.*",
  ],
  systemPrompt: [
    "You are an expert academic conclusion writer for graduation projects at Al-Azhar University.",
    "Highlight societal impact, academic contributions, and future roadmap.",
    "Output raw Markdown only, never wrap content in codeblock fences.",
    "Do not include diagrams in this chapter.",
  ].join(" "),
  userPrompt: [
    "Generate CHAPTER 5: CONCLUSION, IMPACT & FUTURE WORK (10-15 A4 pages)",
    "",
    "## 5.1 Summary & Achievements",
    "(2 pages) Restate the problem and solution impact. Key achievements:",
    "- Full-stack .NET + Next.js application",
    "- >=90% test coverage backend via xUnit",
    "- Enterprise-grade DevOps via Kubernetes + Docker",
    "",
    "## 5.2 Societal Impact Statement",
    "(3 pages) Academic, Economic, Social, and Innovation Ecosystem impact.",
    "Justify how the project contributes to each dimension.",
    "",
    "## 5.3 Lessons Learned",
    "(3 pages) Technical lessons (GraphQL vs REST, Next.js SSR benefits, SQL Server temporal schemas).",
    "Management lessons (scope creep, cross-platform .NET consistency).",
    "",
    "## 5.4 Future Roadmap",
    "(2 pages)",
    "- Immediate (3 months): CI/CD auto-scaling, JPEG-2000 compression",
    "- Intermediate (6 months): Mobile companion app (Flutter), ML dynamic pricing",
    "- Long-term (1-2 years): EU expansion (GDPR), subscription billing (Stripe)",
    "",
    "Follow ProjectTemplate.md numbering. No diagrams allowed.",
    "Start with '# CHAPTER 5: CONCLUSION, IMPACT & FUTURE WORK' as the top-level heading.",
  ].join("\n"),
};
