import type { ChapterConfig } from "../chapters";

export const chapter3: ChapterConfig = {
  id: "3",
  filename: "chapter_3_system_design.md",
  title: "System Design & Architecture",
  heading: "CHAPTER 3: SYSTEM DESIGN & ARCHITECTURE",
  includePatterns: [
    "backend/Api/**/*.cs",
    "backend/Core/**/*.cs",
    "backend/Shared/**/*.cs",
    "frontend/src/**/*.ts",
    "frontend/src/**/*.tsx",
    "frontend/src/**/*.css",
    "frontend/providers/**",
    "!**/*.test.*",
    "!**/*.spec.*",
    "!**/node_modules/**",
    ".github/workflows/**",
  ],
  systemPrompt: [
    "You are an expert academic documentation writer for a graduation project at Al-Azhar University,",
    "Faculty of Engineering, Systems & Computers Department. You write in formal academic English",
    "following the university's rubric guidelines. Output raw Markdown only, never wrap content in",
    "codeblock fences. ALL diagrams MUST be in Mermaid syntax inside codeblocks. Follow proper",
    "Figure X.x referencing for every diagram. Follow UML best practices. Page target: 20-25 A4 pages.",
  ].join(" "),
  includeDiagrams: true,
  userPrompt: [
    "Generate CHAPTER 3: SYSTEM DESIGN & ARCHITECTURE",
    "",
    "## 3.1 Introduction",
    "(0.5 pages) Overview of the chapter and its purpose in proving architectural rigor.",
    "",
    "## 3.2 System Context (C4 Model - Mermaid)",
    "(2 pages) Show all actors (Guest, Client, Admin) and external systems (AWS SES, S3, Payment Gateway).",
    "Include a Mermaid flowchart showing how users and external systems interact with the application.",
    "Reference: Figure 3.2: System Context showing interaction with external services and actors.",
    "",
    "## 3.3 Component / Layered Architecture (Mermaid)",
    "(5 pages) Break down into frontend, backend, database layers.",
    "Map exact technologies (Next.js, .NET Core, SQL Server).",
    "Include a Mermaid graph showing the layered architecture with technology mapping.",
    "Reference: Figure 3.3.a: Layered architecture showing technology stack mapping.",
    "",
    "## 3.4 Database Schema (ERD - Mermaid)",
    "(10 pages) Full Entity-Relationship Diagram in Mermaid erDiagram syntax.",
    "Include ALL tables/entities with their fields, data types, constraints (PK/FK).",
    "Show all relationships (one-to-many, many-to-many).",
    "Describe each entity, field data types, constraints, and sample data.",
    "Reference: Figure 3.4: Entity-Relationship Diagram showing all entities and relationships.",
    "",
    "## 3.5 API Documentation",
    "(15 pages) Table of ALL RESTful endpoints (minimum 30):",
    "| Method | Endpoint | Description | Payload Format | Response Format | Status Codes |",
    "Provide complete request/response examples for all key endpoints.",
    "",
    "## 3.6 Technology Stack Justification",
    "(3 pages) Justify every major technology choice:",
    "- Frontend: Next.js - server-side rendering crucial for SEO in the booking portal.",
    "- Backend: .NET Core - enterprise-grade performance, seamless SQL Server integration.",
    "- Database: SQL Server - ACID compliance essential for financial transactions.",
    "- Infrastructure: Docker/Kubernetes - scalable, reproducible deployments.",
    "",
    "## 3.7 Architecture Decision Records (ADRs)",
    "(5 pages) Bullet-list every critical decision with rationale:",
    "- JWT Authentication - lightweight, stateless, scalable for REST services.",
    "- GraphQL considered but rejected - REST+Swagger better tooling for team size.",
    "- SOLID Principles - maintainable, extensible codebase.",
    "- Microservices considered but rejected - monolith with clean layers sufficient for graduation project.",
    "- UTC Time for Backend - prevents daylight-saving timezone bugs in booking calculations.",
    "",
    "## 3.8 Key Algorithms and Workflows (Mermaid)",
    "(10 pages) Include Mermaid flowcharts for:",
    "- Booking Checkout Workflow (validate, calculate price, process payment, generate invoice)",
    "- Image Upload Pipeline (resize, compress, upload to S3, persist URL)",
    "- Notification System (SES template logic for booking confirmation)",
    "Reference: Figure 3.8.a: Booking workflow showing checkout algorithm and error handling.",
    "",
    "## 3.9 User Interface Design",
    "Describe the frontend architecture, component hierarchy, state management approach, and key UI/UX decisions.",
    "",
    "Do not list every minor function; focus on architectural and implementation significance.",
    "ALL diagrams must be Mermaid inside codeblocks with Figure X.x references.",
    "Start with '# CHAPTER 3: SYSTEM DESIGN & ARCHITECTURE' as the top-level heading.",
  ].join("\n"),
};
