import type { ChapterConfig } from "../chapters";

export const chapter7: ChapterConfig = {
  id: "7",
  filename: "chapter_7_deployment.md",
  title: "Deployment & Operations",
  heading: "CHAPTER 7: DEPLOYMENT & OPERATIONS",
  includePatterns: [
    "README.md",
    "scripts/setup/**/*",
    ".github/workflows/**",
    "backend/**/*.csproj",
    "frontend/package.json",
    "package.json",
  ],
  systemPrompt: [
    "You are an academic DevOps writer generating CHAPTER 7 - the exact replication manual",
    "for running this system in production and development at Al-Azhar University.",
    "Output raw Markdown only.",
    "ALL infrastructure diagrams MUST be in Mermaid syntax inside codeblocks, referencing Figure 7.x.",
  ].join(" "),
  userPrompt: [
    "Generate CHAPTER 7: DEPLOYMENT & OPERATIONS - The DevOps Manual (15-20 A4 pages)",
    "",
    "This chapter MUST enable someone other than the authors to reproduce and run the application.",
    "",
    "## 7.1 Infrastructure Map (Mermaid)",
    "(5 pages) Physical architecture diagram in Mermaid showing:",
    "Cloud hosting (NCP), VPN/VPC, Load Balancer, CDN, Backend Instances, Database Cluster, Email Service.",
    "Include instance counts, port numbers, and health probe configurations.",
    "Reference: Figure 7.1.a: Physical infrastructure map.",
    "",
    "## 7.2 Prerequisites",
    "(2 pages) Full setup for Ubuntu, Windows (choco), and macOS (brew):",
    "Node.js >=18, .NET SDK 7.0+, Docker, SQL Server, Bun.",
    "Include version verification commands.",
    "",
    "## 7.3 Setup Guide",
    "(10 pages) Step-by-step instructions:",
    "Step 1: Clone repository and configure environment variables",
    "Step 2: Database setup (migrations, seeding)",
    "Step 3: Backend build and run",
    "Step 4: Frontend build and run",
    "Step 5: Production containerization with Docker",
    "Include bash/powershell code blocks for each step.",
    "",
    "## 7.4 Monitoring & Observability",
    "(5 pages) Log aggregation, error tracking (Sentry), performance monitoring.",
    "Include Mermaid diagram of error pipeline.",
    "Reference: Figure 7.4.a: Error tracking pipeline.",
    "",
    "## 7.5 Rollback & Recovery Procedures",
    "(2 pages) Blue-green deployment strategy, rollback scripts.",
    "",
    "ALL diagrams must be Mermaid inside codeblocks with Figure 7.x references.",
    "Start with '# CHAPTER 7: DEPLOYMENT & OPERATIONS' as the top-level heading.",
  ].join("\n"),
};
