import type { ChapterConfig } from "../chapters";

export const chapter4: ChapterConfig = {
  id: "4",
  filename: "chapter_4_results.md",
  title: "Results, Testing & Quality Assurance",
  heading: "CHAPTER 4: RESULTS, TESTING & QUALITY ASSURANCE",
  includePatterns: [
    "README.md",
    "package.json",
    "frontend/package.json",
    ".github/workflows/**",
    "frontend/cypress/**",
    "backend/**/*Tests.cs",
    "scripts/run-ci-tests.ps1",
  ],
  systemPrompt: [
    "You are a testing, QA, and results documentation expert for a graduation project at Al-Azhar University.",
    "Output raw Markdown only. Include technical metrics and Mermaid diagrams where applicable.",
    "ALL diagrams MUST be in Mermaid syntax inside codeblocks, referencing Figure X.x.",
  ].join(" "),
  userPrompt: [
    "Generate CHAPTER 4: RESULTS, TESTING & QUALITY ASSURANCE (20-25 A4 pages)",
    "",
    "## 4.1 Feature Completeness Matrix",
    "(5 pages) Table mapping all Chapter 1 functional requirements to implementation status:",
    "| Functional Requirement ID | Requirement Description | Status | Evidence |",
    "Include a Mermaid pie chart showing feature completion rate.",
    "Reference: Figure 4.1.b: Feature completeness dashboard.",
    "",
    "## 4.2 Performance Benchmarks",
    "(5 pages) Backend latency table (average, 95th percentile, error rate, throughput).",
    "Frontend Lighthouse scores table (Performance, Accessibility, Best Practices, SEO) for 5 key pages.",
    "Reference: Figure 4.2.a: Lighthouse performance report.",
    "",
    "## 4.3 Testing Strategy",
    "(3 pages) Unit testing (xUnit for backend, Jest for frontend), Integration testing,",
    "E2E testing (Cypress), Manual testing. Coverage targets: backend >=90%, frontend >=85%.",
    "",
    "## 4.4 Test Cases Matrix",
    "(10 pages) Full test case regression suite in markdown table:",
    "| Test ID | Feature Area | Input Data | Expected Result | Actual Result | Tool | Passed |",
    "Include test automation pipeline Mermaid diagram.",
    "Reference: Figure 4.4.c: Test automation pipeline.",
    "",
    "## 4.5 CI/CD Pipeline (Mermaid)",
    "(3 pages) GitHub Actions pipeline flowchart:",
    "Commit -> GitHub Actions -> Unit Tests -> E2E Tests -> Build Docker Image -> Deploy to Staging",
    "Reference: Figure 4.5.a: CI/CD pipeline.",
    "",
    "## 4.6 Discussion",
    "Be completely honest about deficiencies and inadequacies. Include security audit results.",
    "Reference: Figure 4.6: Security vulnerability assessment matrix.",
    "",
    "ALL diagrams must be Mermaid inside codeblocks with Figure X.x references.",
    "Start with '# CHAPTER 4: RESULTS, TESTING & QUALITY ASSURANCE' as the top-level heading.",
  ].join("\n"),
};
