version: "0.2"
language: en
import:
  - "@cspell/dict-ar/cspell-ext.json"
words:
  - tsgo
  - tsconfig
  - dotnet
  - mssql
  - sqlcmd
  - nextauth
  - NEXTAUTH
  - ASPNETCORE
  - Bun
  - prompts
  - ora
  - zod
  - Ares
  - devcontainer
  - kiro
  - shinawy
  - Substep
  - pids
  - Passw
  - changeme
  - Paymob
  - paymob
  - authtoken
  - ngrok
  - winget
  - taskkill
  - fuser
  - Fuser
  - NVARCHAR
  - executesql
